use_frameworks!

platform :ios, '11.0'

target 'PMSCalendar_Example' do
  pod 'PMSCalendar', :path => '../'
  pod 'PMSPresentation'

  target 'PMSCalendar_Tests' do
    inherit! :search_paths

    
  end
end
